title: Correlation Between Carbon Dioxide Emissions and Temperature in the United States
description: Cameron Hendry and Eli Buffington
show_downloads: false
google_analytics:
theme: jekyll-theme-cayman
